### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by salomanov** [pierreavn/websheetjs#1]
Please tell me what needs to be done to use Cyrillic font in the table?

**Comment by pierreavn** [comment]
Did you found your answer to the problem?

**Comment by salomanov** [comment]
Thanks for the quick response.  It turns out I'm just stupid.  When I entered the Cyrillic alphabet, the text disappeared, so it seemed to me.  in fact, it was simply mounted, and the Cyrillic alphabet simply went down
